#include "creport.h"

CReport::CReport()
{
}

void CReport::showReport()
{
    cout << "===============================================================================" << endl;
    cout << "Report generated by:   " << QDateTime::currentDateTime().toString().toStdString() << endl;
    cout << "Report created on:     " << getenv("USER") << endl;
    cout << "===============================================================================" << endl;
    cout << "Report Summary:        " << endl;
    cout << "===============================================================================" << endl;

    cout << "Host name:             " << getenv("HOSTNAME") << endl;

    cout << "Added objects:         " << addedItems_.count() << endl;
    cout << "Modified objects:      " << changedItems_.count() << endl;
    cout << "Deleted objects:       " << deletedItems_.count() << endl;
    cout << "===============================================================================" << endl << endl;

    if (addedItems_.count() > 0) {
        cout << "Added:" << endl;

        foreach(QString key, addedItems_.keys()){
            cout << addedItems_[key].toStdString() << endl;
        }
        cout << endl;
    }
    if (changedItems_.count() > 0) {
        cout << "Modified:" << endl;

        foreach(QString key, changedItems_.keys()){
            cout << changedItems_[key].toStdString() << endl;
        }
        cout << endl;
    }
    if (deletedItems_.count() > 0) {
        cout << "Deleted:" << endl;

        foreach(QString key, deletedItems_.keys()){
            cout << deletedItems_[key].toStdString() << endl;
        }
        cout << endl;
    }
    cout << "*** End of report ***" << endl;
}
void CReport::setAddedItems(QHash<QString, QString> data)
{
    addedItems_ = data;
}
void CReport::setChangedItmes(QHash<QString, QString> data)
{
    changedItems_ = data;
}
void CReport::setDeletedItmes(QHash<QString, QString> data)
{
    deletedItems_ = data;
}
